guests = ['父亲', '母亲', '老婆']
print(f'一起吃饭吗，{guests[0]}?')
print(f'一起吃饭吗，{guests[1]}?')
print(f'一起吃饭吗，{guests[2]}?')
print(f'{guests[2]}无法赴约')
guests.pop()
guests.append('老公')
print(f'一起吃饭吗，{guests[0]}?')
print(f'一起吃饭吗，{guests[1]}?')
print(f'一起吃饭吗，{guests[2]}?')