guests = ['父亲', '母亲', '老婆']
print(f'一起吃饭吗，{guests[0]}?')
print(f'一起吃饭吗，{guests[1]}?')
print(f'一起吃饭吗，{guests[2]}?')
print(f'{guests[2]}无法赴约')
guests.pop()
guests.append('老公')
print(f'一起吃饭吗，{guests[0]}?')
print(f'一起吃饭吗，{guests[1]}?')
print(f'一起吃饭吗，{guests[2]}?')
print('找到了一个更大的餐桌')
guests.insert(0, '爷爷')
guests.insert(2, '奶奶')
guests.append('外公')
print(f'一起吃饭吗，{guests[0]}?')
print(f'一起吃饭吗，{guests[1]}?')
print(f'一起吃饭吗，{guests[2]}?')
print(f'一起吃饭吗，{guests[3]}?')
print(f'一起吃饭吗，{guests[4]}?')
print(f'一起吃饭吗，{guests[5]}?')
print('只能邀请两位')
guest_pop = guests.pop()
print(f'抱歉不能邀请你吃饭了，{guest_pop}')
guest_pop = guests.pop()
print(f'抱歉不能邀请你吃饭了，{guest_pop}')
guest_pop = guests.pop()
print(f'抱歉不能邀请你吃饭了，{guest_pop}')
guest_pop = guests.pop()
print(f'抱歉不能邀请你吃饭了，{guest_pop}')
print(f'你依然在受邀人之列，{guests[0]}')
print(f'你依然在受邀人之列，{guests[1]}')
del guests[0]
del guests[0]
print(guests)