places = ['beijing', 'tianjin', 'chongqing', 'shanghai', 'hongkong']
print(places)
print(sorted(places))
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse=True)
print(places)